# Generated by Django 3.2.12 on 2023-02-19 06:35

import VideoAI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=VideoAI.models.content_file_name)),
            ],
        ),
    ]
